/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5577d733-5cb3-4dfa-8c24-8644f33075a5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VZkCqZET6",
    "aws_user_pools_web_client_id": "48b9mi5ee7mkrsen77i9nhva2e",
    "oauth": {
      "domain":"acc1.auth.us-east-1.amazoncognito.com",
      "scope": [
        "phone",
        "email",
        "openid",
        "profile",
        "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "https://portal.accencio.com/session/ip",
    "redirectSignOut": "https://portal.accencio.com/session/loginone",
    "responseType": "code"
    },
    "bots": {
        "accewb": {
          "name": "accewb",
          "alias": "$LATEST",
          "region": "us-east-1",
        }
      }
};


export default awsmobile;
